" ============ General Config ===============

set nocompatible                         " Use Vim settings, rather than Vi settings.
filetype plugin indent on                " Load ftplugins and indent files
syntax on                                " Enable syntax highlighting

if has('unnamedplus')
  set clipboard=unnamed,unnamedplus      " Share clipboard between Vim and OS
endif

set number                               " Line number are good
set relativenumber                       " Relative number to quickly run command
set history=10000                        " Set command line history limit
set showcmd                              " Show incomplete commands at the bottom
set showmode                             " Show current mode at the bottom

"\\ encoding
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,sjis,euc-jp,default

set cursorline
set shell=zsh
set splitright
set splitbelow
set mouse=a

"\\ search
set incsearch                            " Find the next match as we type the search
set hlsearch                             " Highlight searches by default
set ignorecase                           " Search case insensitive
set smartcase                            " But not when contain a uppercase char

"\\ Turn on wild menu
set wildmenu
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

"\\ Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

"================ Vundle =====================

set rtp+=~/.vim/bundle/Vundle.vim,~/.fzf
call vundle#begin()

"\\ Vim behavior plugin
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'rking/ag.vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
" Plugin 'scrooloose/syntastic'
Plugin 'Townk/vim-autoclose'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
" Plugin 'junegunn/fzf.vim'
Plugin 'kien/ctrlp.vim'

"\\ Vim apperance
Plugin 'scrooloose/nerdtree'
Plugin 'jpo/vim-railscasts-theme'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'benmills/vimux'

"\\ Vim motion
Plugin 'easymotion/vim-easymotion'
Plugin 'takac/vim-hardtime'

" More operator for vim
Plugin 'tpope/vim-surround'                     "s command like surround
Plugin 'vim-scripts/ReplaceWithRegister'        "gr to replace with yanked text

" Vim Text object
Plugin 'michaeljsmith/vim-indent-object'        "For ident object like python coffescript: ii and ai
Plugin 'kana/vim-textobj-user'                  "Addition to use vim text obj rubyblock
Plugin 'nelstrom/vim-textobj-rubyblock'         "Ruby text object: ir and ar
Plugin 'kana/vim-textobj-line'                  "Line textobj: al and il
Plugin 'whatyouhide/vim-textobj-erb'            "erb text object: aE and iE
Plugin 'machakann/vim-textobj-delimited'        "Delimited text object: ad and id

"\\ Vim for ruby dev
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-bundler'
Plugin 'thoughtbot/vim-rspec'

"\\ Vim for front-end dev
Plugin 'mattn/emmet-vim'

"\\ Markdown
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

"\\ Ctags
Plugin 'craigemery/vim-autotag'

"\\ Other Plugin
Plugin '907th/vim-auto-save'
call vundle#end()


" ================ Apperance ====================

set numberwidth=3
set t_Co=256
colorscheme railscasts
set guifont=C@nsolas:h12:w6
set guifont=inconsolata
set guifontwide=FixedSys:h18
set guioptions=egmrL
set tw=80
set showbreak=...                                 " Display ... as wrap break
set showmatch
set wrap linebreak nolist                         " Proper wrapping

"\\ Folding settings
" Use zi, za, zc, zR, zM, zv
set foldmethod=indent                             " Groups of lines with the same indent form a fold
set foldnestmax=3                                 " Set deepest folding to 3 levels
set nofoldenable                                  " Don't fold by default


" ================ Behavior =====================

"\\ Centralize backup, swap and undo file
set noswapfile
set nobackup
set nowb
au FocusLost * :wa

"\\ Auto save files
autocmd BufLeave, FocusLost * silent! wall         " Some terminal doesn't support FoucusLost
inoremap <Esc> <Esc>:w<CR>

"\\ Check file change and reload every 4 seconds
set autoread
au CursorHold * checktime

"\\ Y to copy to end of line
map Y y$

"\\ Indentation settings
set tabstop=2 shiftwidth=2 expandtab autoindent

"\\ Allow backspacing over everything in insert mode
set backspace=indent,eol,start

"\\ ex_mode
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

"\\ Ignore redraw when using tmux
if &term =~ '256color'
  set t_ut=
endif


" ================ Mappings ====================

let mapleader=" " " Set Space for Leader key

"\\ Resizing Windows
nnoremap <Leader><Leader>= <C-w>=
nnoremap <Leader><Leader>k <C-w>+10
nnoremap <Leader><Leader>j <C-w>-10
nnoremap <Leader><Leader>h <C-w><10
nnoremap <Leader><Leader>l <C-w>>10

"\\ Switch between panels
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

"\\ Operator with a panel
nnoremap <Leader>t :tabnew<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>x :x<CR>
nnoremap <Leader>o :e<Space>
nnoremap <Leader>p o<ESC>p`[v`]

"\\ Disable arrow key
map <Left> :echo "no!"<cr>
map <Right> :echo "no!"<cr>
map <Up> :echo "no!"<cr>
map <Down> :echo "no!"<cr>

"\\ Quickly select text you just pasted
noremap gV `[v`]

"\\ Search
nnoremap <Leader>n :noh<CR>

"\\ Insert pasted text at end of lineend
nnoremap <Leader>eol $p

"\\ Vim file
nmap <Leader>v :e ~/.vimrc<CR> " Quickly edit .vimrc file
noremap <Leader><Leader>s :so ~/.vimrc<CR> " Source .vimrc file

"\\ Switch between files
nnoremap <tab> :bp<CR> " Previous buffer file
nnoremap <S-tab> :bn<CR> " Next buffer file
nnoremap <Leader><Leader>c <c-^> " The last two files

"\\ Select all file
nnoremap <Leader>a ggVG

" Remap VIM 0 to first non-blank character
map B ^
map E $

nnoremap c<space> ct<space>
" Use ; instead of :
" nmap ; :

" Move a line of text using ALT+[jk]
nmap <Leader>j mz:m+<cr>`z
nmap <Leader>k mz:m-2<cr>`z
vmap <Leader>j :m'>+<cr>`<my`>mzgv`yo`z
vmap <Leader>k :m'<-2<cr>`>my`<mzgv`yo`z

"---------------  Make Vim like IDE -------------------------
"---------------  Run, Forrest, Run -------------------------

"\\ Python
nnoremap <buffer> <F9> :exec '!python' shellescape(@%, 1)<cr>

"\\ C
nnoremap <Leader>i :!gcc -o .a.out % && ./.a.out<CR>

"\\ Ruby
nmap <Leader>E :!ruby %<cr>


"=============== Extends behaviors =========================

"\\ Quick swap character, word and paragraph
nnoremap <silent> gw "_yiw:s/\(\%#\w\+\)\(\W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>
nnoremap <silent> gw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>
nnoremap g{ {dap}p{

" Change cusor shape in different mode
au VimLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
" au VimEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"

"\\ Delete all trailing space when saving file
autocmd BufWritePre * :%s/\s\+$//e

"\\ Force save file when I forgot run 'sudo vim file'
"\\ With Great Power Comes Great Responsibility
cmap w!! %!sudo tee > /dev/null %

"\\ Create folder
map <Leader>cf :!mkdir -p<Space>

" ================ Plugin Config ====================

"\\ Vundle
nnoremap <Leader>P :so %<CR>:PluginInstall<CR>:q<CR>

"------------------------------------------------------

"\\ Rails.vim
map <Leader>rg :Rails generate<space>
map <Leader>rd :Rails destroy<space>

map <Leader>em :Emodel<space>
map <Leader>ev :Eview<space>
map <Leader>ec :Econtroller<space>
map <Leader>eh :Ehelper<space>
map <Leader>el :Elib<space>
map <Leader>er :Emailer<space>

map <Leader>ej :Ejavascript<space>
map <Leader>es :Estylesheet<space>
map <Leader>ey :Elayout<space>

map <Leader>ee :Eenvironment<space>
map <Leader>ei :Einitializer<space>
map <Leader>ew :Emigration<space>
map <Leader>ed :Eschema

map <Leader>ef :Efixtures<space>
map <Leader>eu :Eunittest<space>
map <Leader>et :Efunctionaltest<space>

"------------------------------------------------------

"\\ Autosave
let g:auto_save = 1
let g:auto_save_silent = 1
let g:auto_save_in_insert_mode = 0

"------------------------------------------------------

"\\ Emmet-vim
imap hh <C-y>,

"------------------------------------------------------

"\\ AutoClose
" Bring back Up and Down key in Insert Mode
if !has("gui_running")
  let g:AutoClosePreservDotReg = 0
endif

"------------------------------------------------------

"\\ NERDTree
map <F5> :NERDTreeToggle<CR>
" autocmd VimEnter * NERDTree
" autocmd VimEnter * wincmd p

"------------------------------------------------------

"\\ Vim Commentary
nmap cm gc

"------------------------------------------------------

"\\ You Complete Me
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
set shortmess+=c

"------------------------------------------------------

"\\ Ruby txet object
runtime macros/matchit.vim

"------------------------------------------------------

"\\ Syntastic
set statusline+=%#warningmsg#
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"------------------------------------------------------

"\\ Ack
map <Leader>g :Ag<Space>
let g:ag_working_path_mode="r"
set grepprg=ag
let g:grep_cmd_opts = '--line-numbers --noheading'

"------------------------------------------------------

"\\ UltiSnips
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<c-l>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

"------------------------------------------------------

"\\ Vim Hardmode
nnoremap <Leader>y <Esc>:call ToggleHardMode()<CR>
" let g:hardtime_default_on = 1
" let g:hardtime_maxcount = 3

"------------------------------------------------------

"\\ Vim Airline
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

"------------------------------------------------------

"\\ Easy Motion
let g:EasyMotion_do_mapping = 0
map <Leader> <Plug>(easymotion-prefix)
" nmap s <Plug>(easymotion-overwin-f2)
map <Leader>L <Plug>(easymotion-bd-jk)
nmap <Leader>L <Plug>(easymotion-overwin-line)
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>W <Plug>(easymotion-overwin-w)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>h <Plug>(easymotion-linebackward)

"------------------------------------------------------

"\\ RSpec.vim
nnoremap <Leader>rs :call RunCurrentSpecFile()<CR>
nnoremap <Leader>ras :call RunAllSpecs()<CR>
map <Leader>rns :call RunNearestSpec()<CR>
map <Leader>rl :call RunLastSpec()<CR>

"------------------------------------------------------

"\\ Vim Fugitve
nnoremap <Leader>bl :Gblame<CR>

"------------------------------------------------------

" "\\ FZF
" nnoremap <C-p> :Files<CR>
" imap <c-x><c-l> <plug>(fzf-complete-line)
" nnoremap <Leader>fc :Commits<CR>
" nnoremap <Leader>fC :BCommits<CR>
" nnoremap <Leader>fl :Lines<CR>
" nnoremap <Leader>ft :Tags<CR>
" nnoremap <Leader>fh :History:<CR>
" nnoremap <Leader>fH :History/<CR>

"------------------------------------------------------

"\\ Ctags
" autocmd BufWritePost *  :UpdateTags
" nnoremap <f5> :!ctags -R --exclude=.git --exclude=log *<cr>


" ================ My Extend Functions ====================

"\\ Auto refresh firefox active tab when I save a file, require refresh_browser.sh script

" autocmd BufWriteCmd *.html,*.css,*.rb,*.erb :call Refresh_browser()
function! Refresh_browser()
  if &modified
    write
    silent !refresh_firefox
  endif
endfunction

"\\ Auto close windows when COMMIT_EDITMSG git file --> Quickly push + rebase with git
function! Close_git_message()
  let l:filename = @%
  if (filename == ".git/COMMIT_EDITMSG")
    execute 'quitall'
  endif
endfunction
autocmd VimEnter * :call Close_git_message()
