# Non interactive app will load source in this file. So I move this function
# here to Vim can using it

goGithubLine() {
  file_name=$1
  line=$2
  repo_url=$(git config --get remote.upstream.url)
  repo_name=(${=repo_url//:/ })    # Zsh split string to arr T.T
  rn=(${=repo_name[2]//./ })
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "https://github.com/${rn[1]}/blob/master/${file_name}#L${line}"
}

goGithubCommit() {
  commit_hash=$1
  repo_url=$(git config --get remote.upstream.url)
  repo_name=(${=repo_url//:/ })    # Zsh split string to arr T.T
  rn=(${=repo_name[2]//./ })
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "https://github.com/${rn[1]}/commit/${commit_hash}"
}

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:/usr/local/bin:$PATH"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
eval "$(pyenv virtualenv-init -)"
