# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Dotfiles folder
export DOTFILES=~/Dropbox/Projects/dotfiles

# Ack like vim
bindkey -v

ZSH_THEME="agnoster"

export UPDATE_ZSH_DAYS=7

# Plugin
plugins=(zsh-autosuggestions vi-mode z)

# User configuration
export PATH="$HOME/.rvm/bin:$HOME/go/bin:/usr/local/bin:/usr/bin:/usr/local/opt/mysql@5.7/bin:/usr/local/Cellar/postgresql@9.6/9.6.19/bin:/usr/local/opt/python@3.8/bin:$HOME/google-cloud-sdk/bin:$PATH"

export EDITOR="nvim"
export TERM="xterm-256color"

zstyle ':omz:update' mode disabled
source $ZSH/oh-my-zsh.sh

# Alias
source $DOTFILES/zsh/alias.zsh
source $DOTFILES/zsh/functions.zsh

# FZF functions
source $DOTFILES/zsh/fzf.zsh

# Allow [ or ] whereever you want
unsetopt nomatch

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey '^ ' autosuggest-execute

source ~/.zshrc.private

prompt_dir() {
  shorten_path=$(echo $PWD | perl -pe "s/(\w)[^\/]+\//\1\//g")
  prompt_segment blue $CURRENT_FG $shorten_path
  # prompt_segment blue $CURRENT_FG ' %20<...<%~%<< '
}
